---
image:
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2022-datacenter-azure-edition
  version: 20348.2402.240405 ## April 2024 https://support.microsoft.com/en-us/topic/windows-server-images-for-april-2024-3c03f503-9658-4c20-9d34-a4ff25d8b319
sharedimage:
  gallery_name: ""
  image_name: ""
  image_version: ""
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralus
    - northcentralus
    - eastus
    - eastus2
    - southcentralus
    - westus
    - westus2
vm:
  puppet_version: 6.28.0
  size: Standard_F32s_v2
  tags:
    base_image: win2022642009azure
    worker_pool_id: trusted-win2022-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: cloud_windows
    deploymentId: b1285eb
    managed_by: packer
tests:
  - microsoft_tools_builder.tests.ps1
  - disable_services_builder.tests.ps1
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - logging.tests.ps1
  - common_tools.tests.ps1
  - google_auth.tests.ps1
  - git.tests.ps1
  - mozilla_build_builder.tests.ps1