---
image:
  source_image_family: ubuntu-2404-lts-amd64
  project_id: firefox-production-level1-workers
  image_name: ubuntu2204-alpha
  zone: us-west1-a
vm:
  disk_size: 100
  taskcluster_version: 68.0.4
  tc_arch: AMD64
