---
image:
  source_image_family: ubuntu-2404-lts-amd64
  project_id: "taskcluster-imaging"
  workload_identity_provider_project_number: 324168772199
  image_name: ubuntu2204-amd64-alpha
  zone: us-west1-a
vm:
  disk_size: 100
  taskcluster_version: 69.0.1
  tc_arch: AMD64
