---
image:
  publisher: MicrosoftWindowsDesktop
  offer: windows11preview-arm64
  sku: win11-24h2-ent
  version: latest
sharedimage:
  gallery_name: ""
  image_name: ""
  image_version: ""
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralus
vm:
  puppet_version: 8.5.1
  git_version: 2.46.0
  size: Standard_D8ps_v5
  tags:
    base_image: win11a6424h2azurebuilder
    worker_pool_id: win11-a64-24h2-builder-alpha
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: win11Aarch64
    deploymentId: "4ccc087"
    managed_by: packer
tests:
  - microsoft_tools_builder-a64.tests.ps1
  - disable_services_builder.tests.ps1
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - logging.tests.ps1
  - common_tools.tests.ps1
  - google_auth.tests.ps1
  - git.tests.ps1
  - mozilla_build_builder.tests.ps1
  - windows_worker_runner.tests.ps1
