---
image:
  publisher: MicrosoftWindowsDesktop
  offer: Windows-11
  sku: win11-22h2-avd
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - canadacentral
    - centralindia
    - centralus
    - eastus
    - eastus2
    - northcentralus
    - northeurope
    - southindia
    - westus
    - westus2
    - westus3
vm:
  size: Standard_F8s_v2
  tags:
    base_image: win11642009azure
    worker_pool_id: win11-64-2009
    sourceOrganisation: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: cloud_windows
    deploymentId: 1416118
    managed_by: packer