---
image:
  publisher: MicrosoftWindowsDesktop
  offer: Windows-10
  sku: win10-22h2-avd
  version: 19045.3570.231001 ## October 2023 https://support.microsoft.com/en-au/topic/windows-10-and-windows-11-client-images-for-october-2023-cca47fce-a048-4239-9e54-a6f346ba6480
  gallery_name: "ronin_t_windows10_64_2009_alpha"
  image_name: "win10-64-2009-alpha"
  image_version: 1.0.0
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - ukwest
vm:
  size: Standard_F8s_v2
  tags:
    base_image: win10642009azure
    worker_pool_id: win10-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: cloud_windows
    deploymentId: 1c1a301
    managed_by: packer
tests:
  - git.tests.ps1