---
image:
  publisher: MicrosoftWindowsDesktop
  offer: Windows-10
  sku: win10-22h2-avd
  version: 19045.3324.230728 ## https://support.microsoft.com/en-us/topic/windows-10-and-windows-11-client-images-for-august-2023-40485b69-f481-4353-aa61-d92c238c7a1d
sharedimage:
  gallery_name: "ronin_t_windows10_64_2009_alpha"
  image_name: "win10-64-2009-alpha"
  image_version: 1.0.0
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - uksouth
    # - centralindia
    # - eastus
    # - eastus2
    # - northcentralus
    # - northeurope
    # - southindia
    # - southcentralus
    # - westus
    # - westus2
    # - westus3
  bootstrapscript: "https://raw.githubusercontent.com/mozilla-platform-ops/ronin_puppet/cloud_windows/provisioners/windows/azure/azure-bootstrap.ps1"
vm:
  size: Standard_F8s_v2
  tags:
    base_image: win10642009azure
    worker_pool_id: win10-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: cloud_windows
    deploymentId: e343af9
    managed_by: packer
