---
image:
  publisher: MicrosoftWindowsDesktop
  offer: Windows-10
  sku: win10-22h2-avd
  version: 19045.3930.240104 ## January 2024 https://support.microsoft.com/en-us/topic/windows-10-and-windows-11-client-images-for-january-2024-1a2b5966-c246-4961-a424-5eea8a868172
  gallery_name: "ronin_t_windows10_64_2009_alpha"
  image_name: "win10-64-2009-alpha"
  image_version: 1.0.0
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - ukwest
vm:
  size: Standard_F8s_v2
  tags:
    base_image: win10642009azure
    worker_pool_id: win10-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: mozbuild41
    deploymentId: c07c29b
    managed_by: packer
tests:
  - microsoft_tools_tester.tests.ps1
  - disable_services.tests.ps1
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - virtual_drivers.tests.ps1
  - logging.tests.ps1
  - common_tools.tests.ps1
  - git.tests.ps1
  - mozilla_build_tester.tests.ps1
  - mozilla_maintenance_service.tests.ps1
  - windows_worker_runner.tests.ps1