---
image:
  publisher: MicrosoftWindowsDesktop
  offer: Windows-11
  sku: win11-22h2-avd
  version: 22621.1555.230329
sharedimage:
  gallery_name: "ronin_t_windows11_64_2009_prod"
  image_name: "win11-64-2009"
  image_version: 1.0.0
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralindia
    - eastus
    - eastus2
    - northcentralus
    - northeurope
    - southindia
    - southcentralus
    - westus
    - westus2
    - westus3
  bootstrapscript: "https://raw.githubusercontent.com/mozilla-platform-ops/ronin_puppet/cloud_windows/provisioners/windows/azure/azure-bootstrap.ps1"
vm:
  size: Standard_F8s_v2
  tags:
    base_image: win11642009azure
    worker_pool_id: win11-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: cloud_windows
    deploymentId: f4ce3d6
    managed_by: packer
