---
image:
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2022-datacenter-azure-edition
  version: 20348.2031.231006 ## October 2023 https://support.microsoft.com/en-au/topic/windows-server-images-for-october-2023-cb930aa9-4609-48f4-90b2-13767a0f9dcd
sharedimage:
  gallery_name: ""
  image_name: ""
  image_version: ""
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralus
    - northcentralus
vm:
  size: Standard_F32s_v2
  tags:
    base_image: win2022642009azure
    worker_pool_id: win2022-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: cloud_windows
    deploymentId: 1c1a301
    managed_by: packer
