---
image:
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2022-datacenter-azure-edition
  version: 20348.2227.240104 ## January 2024 https://support.microsoft.com/en-us/topic/windows-server-images-for-january-2024-001a10f0-c04b-45f9-9883-f21a78f71cec
sharedimage:
  gallery_name: ""
  image_name: ""
  image_version: ""
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralus
    - northcentralus
vm:
  size: Standard_F32s_v2
  tags:
    base_image: win2022642009azure
    worker_pool_id: win2022-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: mozbuild41
    deploymentId: d1f9018
    managed_by: packer
tests:
  - microsoft_tools_builder.tests.ps1
  - disable_services_builder.tests.ps1
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - logging.tests.ps1
  - common_tools.tests.ps1
  - google_auth.tests.ps1
  - git.tests.ps1
  - mozilla_build_builder.tests.ps1
  - windows_worker_runner.tests.ps1
