---
image:
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2022-datacenter-azure-edition
  version: latest ## June 2023 Updates
sharedimage:
  gallery_name: ""
  image_name: ""
  image_version: ""
azure:
  managed_image_resource_group_name: rg-packer-through-cib
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralus
    - northcentralus
  bootstrapscript: "https://raw.githubusercontent.com/mozilla-platform-ops/ronin_puppet/cloud_windows/provisioners/windows/azure/azure-bootstrap.ps1"
vm:
  size: Standard_F32s_v2
  tags:
    base_image: win2022642009azure
    worker_pool_id: win2022-64-2009
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: bug1845790
    deploymentId: d69ffd6
    managed_by: packer
