name: matrix

on: [workflow_dispatch, push]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          $commit = ConvertFrom-Json '${{toJSON(github.event.head_commit.message)}}'
          $commit
