name: matrix

on: [workflow_dispatch, push]

jobs:
  job1:
    name: "Create Image Tasks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          . .github/workflows/tools.ps1
          Set-WorkerImageOutput -CommitMessage '${{toJSON(github.event.head_commit.message)}}'
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
      KEY: ${{ steps.set-matrix.outputs.KEY }}
  job2:
    needs: job1
    name: "${{ needs.job1.outputs.KEY }} - ${{ matrix.LOCATIONS }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
    steps:
      - uses: actions/checkout@v3
#      - name: Azure Login
#        uses: Azure/login@v1
#        with:
#          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID_DEV }}","clientSecret":"${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
#          enable-AzPSSession: true
#      - name: "List packer stuff"
#        uses: azure/powershell@v1
#        with:
#          inlinescript: |
#            Get-AzResourceGroup -Name "rg-packer-worker-images"
#          azPSVersion: "latest"
      - name: 'Run Packer'
        shell: pwsh
        run: |
          . .github/workflows/tools.ps1
          Set-Location .\windows
          $SHA = "${{toJSON(github.event.after)}}" -replace "''"
          Write-Host "Building '${{ needs.job1.outputs.KEY }}' in '${{ matrix.LOCATIONS }}' from $SHA"
          New-WorkerImage -Location "${{ matrix.LOCATIONS }}" -CommitMessage '${{toJSON(github.event.head_commit.message)}}'