name: matrix

on: [workflow_dispatch, push]

jobs:
  job1:
    name: "Create Image Tasks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          . .github/workflows/tools.ps1
          Set-WorkerImageOutput -CommitMessage '${{toJSON(github.event.head_commit.message)}}'
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
      KEY: ${{ steps.set-matrix.outputs.KEY }}
  job2:
    needs: job1
    name: '${{ needs.job1.outputs.KEY }} - ${{ matrix.LOCATIONS }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID_DEV }}","clientSecret":"${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true
      - run: |
          Get-AzResourceGroup -Name "rg-packer-worker-images"
      - name: Run Command
        shell: pwsh
        env:
          subscription_id = ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
          client_id = ${{ secrets.AZURE_CLIENT_ID }}
          client_secret = ${{ secrets.AZURE_CLIENT_ID_SECRET }}
          tenant_id = ${{ secrets.AZURE_TENANT_ID }}
        run: |
          Set-Location .\windows
          $SHA = ConvertFrom-Json '${{toJSON(github.event.after)}}'
          Write-Host "Building '${{ needs.job1.outputs.KEY }}' in '${{ matrix.LOCATIONS }}' from $SHA"