name: matrix

on: [workflow_dispatch, push]

jobs:
  job1:
    name: "Create Maintenance and Image Build Tasks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          . .github/workflows/tools.ps1
          Set-WorkerImageOutput -CommitMessage '${{toJSON(github.event.head_commit.message)}}'
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
      KEY: ${{ steps.set-matrix.outputs.KEY }}
  job2:
    needs: job1
    name: '${{ matrix.KEY }} - ${{ matrix.LOCATIONS }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
        key: ${{fromJson(needs.job1.outputs.KEY)}}
    steps:
      - uses: actions/checkout@v3
      - name: Run Command
        shell: pwsh
        run: |
          $SHA = ConvertFrom-Json '${{toJSON(github.event.after)}}'
          Write-Host "Running location '${{ matrix.LOCATIONS }}' from $SHA"
