name: matrix

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml -ErrorAction Stop
          $win11642009 = Convertfrom-Yaml (Get-Content "config/win11-64-2009.yaml" -raw)
          $locations = ($win11642009.azure.locations | ConvertTo-Json -Compress)
          Write-Output "LOCATIONS=$locations" >> $ENV:GITHUB_OUTPUT
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
    steps:
      - uses: actions/checkout@v3
      - name: Run Command
        shell: pwsh
        run: |
          Write-Host "Running location '${{ matrix.LOCATIONS }}'"