name: matrix

on: [workflow_dispatch, push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml -ErrorAction Stop
          $Commit = ConvertFrom-Json '${{toJSON(github.event.head_commit.message)}}'
          $keys = $Commit -split ' ' | Foreach-object {
            { if ($_ -match "-") {
                $_
              }
            }
          }
          $YAML = Convertfrom-Yaml (Get-Content "config/$keys.yaml" -raw)
          $locations = ($YAML.azure.locations | ConvertTo-Json -Compress)
          Write-Output "LOCATIONS=$locations" >> $ENV:GITHUB_OUTPUT
          Write-Output "SHA=$PushEvent.after" >> $ENV:GITHUB_OUTPUT
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
      SHA: ${{ steps.set-matrix.outputs.SHA }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
        sha: ${{fromJson(needs.job1.outputs.SHA)}}
    steps:
      - uses: actions/checkout@v3
      - name: Run Command
        shell: pwsh
        run: |
          Write-Host "Running location '${{ matrix.LOCATIONS }}' from ref '${{ matrix.SHA }}'"
