run-name: ${{ github.event.inputs.config }} - FXCI
name: FXCI

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - win10-64-2009-alpha
        - win10-64-2009
        - win11-64-2009-alpha
        - win11-64-2009
        - win2022-64-2009-alpha
        - win2022-64-2009
      releasenotes:
        type: choice
        description: Generate release notes
        options:
        - "true"
        - "false"

jobs:
  job1:
    name: "Create Image Tasks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        shell: pwsh
        run: |
          Import-Module .\bin\WorkerImages\WorkerImages.psm1
          Set-AzWorkerImageLocation -Key '${{ github.event.inputs.config }}'
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
  job2:
    needs: job1
    name: "${{ github.event.inputs.config }} - ${{ matrix.LOCATIONS }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID_FXCI }}","clientSecret":"${{ secrets.AZURE_CLIENT_ID_FXCI_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_UNTRUSTED }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true
      - name: "Remove current images"
        uses: azure/powershell@v2
        with:
          inlinescript: |
            Import-Module .\bin\WorkerImages\WorkerImages.psm1
            Remove-AzWorkerImage -Key "${{ github.event.inputs.config }}" -Location "${{ matrix.LOCATIONS }}"
          azPSVersion: "latest"
      - name: 'Run Packer'
        shell: pwsh
        run: |
          Import-Module .\bin\WorkerImages\WorkerImages.psm1
          $Vars = @{
            Location = "${{ matrix.LOCATIONS }}"
            Key = '${{ github.event.inputs.config }}'
            Client_ID = "${{ secrets.AZURE_CLIENT_ID_FXCI }}"
            Client_Secret = "${{ secrets.AZURE_CLIENT_ID_FXCI_SECRET }}"
            Subscription_ID = "${{ secrets.AZURE_SUBSCRIPTION_ID_UNTRUSTED }}"
            Tenant_ID = "${{ secrets.AZURE_TENANT_ID }}"
            Application_ID = "${{ secrets.AZURE_APPLICATION_ID_FXCI }}"
          }
          New-AzWorkerImage @Vars
  job3:
    if: ${{ inputs.releasenotes == 'true' }}
    needs: job2
    name: "Upload release notes"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Download Release Notes to Github"
        uses: azure/powershell@v2
        with:
          inlinescript: |
              $Config = "${{ github.event.inputs.config }}"
              ## Download the release notes
              $ENV:AZCOPY_AUTO_LOGIN_TYPE = "SPN"
              $ENV:AZCOPY_SPA_APPLICATION_ID = "${{ secrets.AZURE_APPLICATION_ID_FXCI }}"
              $ENV:AZCOPY_SPA_CLIENT_SECRET = "${{ secrets.AZURE_CLIENT_ID_FXCI_SECRET }}"
              $ENV:AZCOPY_TENANT_ID = "${{ secrets.AZURE_TENANT_ID }}"
              Write-host "Downloading Release Notes for $($config).md"
              azcopy copy "https://roninpuppetassets.blob.core.windows.net/packer/$($config).md" "./config/$($config).md"
          azPSVersion: "latest"
      - name: Create Pull Request for Release
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          ## Vars
          $Config = "${{ github.event.inputs.config }}"
          $Date = Get-Date -Format "yyyyMMdd"

          if ($config -match "win10") {
            $ReleaseBranch = "(releases/win10/{0}-docs)" -f $Date
          }
          if ($config -match "win11") {
            $ReleaseBranch = "(releases/win11/{0}-docs)" -f $Date
          }
          if ($config -match "win2022") {
            $ReleaseBranch = "(releases/win2022/{0}-docs)" -f $Date
          }
          
          $branchExists = git branch --list $ReleaseBranch

          if (-not $branchExists) {
            git checkout -b $branchName
            git push origin $branchName
          } else {
            git checkout $branchName
          }
          
          $PR_Body = @"
          # Release Notes for $($config).md

          Automatically generated PR for $($config).md
          "@

          $PR_Title = "$Config ($date) Image Update"

          git add "./config/$($config).md"
          git commit -m "$($Date) - Release Notes for $($config).md"
          git push -u origin $ReleaseBranch
          gh pr create --base main --head $ReleaseBranch --title $PR_Title --body $PR_Body