run-name: ${{ github.event.inputs.config }} - FXCI
name: FXCI

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - win10-64-2009-alpha
        - win10-64-2009
        - win11-64-2009-alpha
        - win11-64-2009
        - win2022-64-2009-alpha
        - win2022-64-2009

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: "Create Image Tasks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
          Set-AzWorkerImageLocation -Key '${{ github.event.inputs.config }}'
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
  job2:
    needs: job1
    name: "${{ github.event.inputs.config }} - ${{ matrix.LOCATIONS }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_FXCI }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_UNTRUSTED }}
          enable-AzPSSession: true
      - name: "Remove current images"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
            Remove-AzWorkerImage -Key "${{ github.event.inputs.config }}" -Location "${{ matrix.LOCATIONS }}"
          azPSVersion: "latest"
      - name: 'Run Packer'
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
          $Vars = @{
            Location = "${{ matrix.LOCATIONS }}"
            Key = '${{ github.event.inputs.config }}'
            Client_ID = "${{ secrets.AZURE_CLIENT_ID_FXCI }}"
            Client_Secret = "${{ secrets.AZURE_CLIENT_ID_FXCI_SECRET }}"
            oidc_request_url = "${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}"
            oidc_request_token = "${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}"
            Subscription_ID = "${{ secrets.AZURE_SUBSCRIPTION_ID_UNTRUSTED }}"
            Tenant_ID = "${{ secrets.AZURE_TENANT_ID }}"
            Application_ID = "${{ secrets.AZURE_APPLICATION_ID_FXCI }}"
          }
          New-AzWorkerImage @Vars
      - name: "Upload Release Notes for ${{ github.event.inputs.config }}"
        uses: azure/powershell@v2  
        with:
          inlineScript: |
            $Config = "${{ github.event.inputs.config }}"
            $exists = Test-Path -Path "${{ github.workspace }}/config/$($config).md"
            if ($null -eq $exists) {
              Write-Host "No release notes found for ${{ github.event.inputs.config }}"
              exit 1
            }
            Write-Host "Release notes found for ${{ github.event.inputs.config }}"
            Write-host "Uploading Release Notes for $($Config).md"
            $ENV:AZCOPY_AUTO_LOGIN_TYPE = "PSCRED"
            azcopy copy "${{ github.workspace }}/config/$($Config).md" "https://roninpuppetassets.blob.core.windows.net/packer"
          azPSVersion: "latest"