name: Shared Image Gallery Deployment - Dev

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - win10-64-2009-alpha
        - win10-64-2009
        - win11-64-2009-alpha
        - win11-64-2009

jobs:
  packer:
    name: "Build ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Run Packer'
        shell: pwsh
        run: |
          . .github/workflows/tools.ps1
          Remove-VMImageVersion -Key '${{ github.event.inputs.config }}'
          $Vars = @{
            Key = '${{ github.event.inputs.config }}'
            Client_ID = "${{ secrets.AZURE_CLIENT_ID_DEV }}"
            Client_Secret = "${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}"
            Subscription_ID = "${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}"
            Tenant_ID = "${{ secrets.AZURE_TENANT_ID }}"
          }
          New-SharedWorkerImage @Vars