name: Shared Image Gallery Deployment - Dev

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - win10-64-2009-alpha
        - win10-64-2009
        - win11-64-2009-alpha
        - win11-64-2009

jobs:
  validate:
    name: "Remove imageversion from ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID_DEV }}","clientSecret":"${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true
      - name: "Remove current images"
        uses: azure/powershell@v2
        with:
          inlinescript: |
            Import-Module .\bin\WorkerImages\WorkerImages.psm1
            Remove-VMImageVersion -Key '${{ github.event.inputs.config }}'
          azPSVersion: "latest"
  packer:
    name: "Build ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Run Packer'
        shell: pwsh
        run: |
          Import-Module .\bin\WorkerImages\WorkerImages.psm1
          $Vars = @{
            Key = '${{ github.event.inputs.config }}'
            Client_ID = "${{ secrets.AZURE_CLIENT_ID_DEV }}"
            Client_Secret = "${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}"
            Subscription_ID = "${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}"
            Tenant_ID = "${{ secrets.AZURE_TENANT_ID }}"
          }
          New-SharedWorkerImage @Vars