name: win11-64-2009-alpha

on: [workflow_dispatch]

jobs:
  job1:
    name: "Create Image Tasks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: pwsh
        # Use a small PowerShell script to generate the test matrix
        run: |
          . .github/workflows/tools.ps1
          Set-WorkerImageOutput -CommitMessage '${{toJSON(github.event.head_commit.message)}}'
    outputs:
      LOCATIONS: ${{ steps.set-matrix.outputs.LOCATIONS }}
      KEY: ${{ steps.set-matrix.outputs.KEY }}
  job2:
    needs: job1
    name: "${{ needs.job1.outputs.KEY }} - ${{ matrix.LOCATIONS }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        locations: ${{fromJson(needs.job1.outputs.LOCATIONS)}}
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID_DEV }}","clientSecret":"${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: true
      - name: "Remove current images"
        uses: azure/powershell@v1
        with:
          inlinescript: |
            . .github/workflows/tools.ps1
            Remove-WorkerImage -Key "${{ needs.job1.outputs.KEY }}" -Location "${{ matrix.LOCATIONS }}"
          azPSVersion: "latest"
      - name: 'Run Packer'
        shell: pwsh
        run: |
          . .github/workflows/tools.ps1
          $SHA = "${{ github.event.after }}"
          Write-Host "Building '${{ needs.job1.outputs.KEY }}' in '${{ matrix.LOCATIONS }}' from $SHA"
          $Vars = @{
            Location = "${{ matrix.LOCATIONS }}"
            Key = '${{ needs.job1.outputs.KEY }}'
            Client_ID = "${{ secrets.AZURE_CLIENT_ID_DEV }}"
            Client_Secret = "${{ secrets.AZURE_CLIENT_ID_DEV_SECRET }}"
            Subscription_ID = "${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}"
            Tenant_ID = "${{ secrets.AZURE_TENANT_ID }}"
          }
          New-WorkerImage @Vars